PImage librocerrado;
PImage libroabierto;
PImage libroabierto1;
PImage paginaabierta;
PImage riuk;
PImage riuk2;
PImage escena1;
PImage escenados;
PImage escena3;
PImage escena4;
PImage escena5;
PImage carariuk;
int tiempoEscenas;
float posTexto = -500;
int escenaActual = 0;
boolean cambiar = false;
boolean mostrarTexto = true;
boolean riukQ = false;
String texto = "ABRIR DEATH NOTE";
String dialogoRiuk = "HOLA HUMANO, ME LLAMO RYUK";
String dialogoRiuk2 = "ENCONTRASTE LA DEATH NOTE...";
String dialogoRiuk3 = "TE EXPLICO COMO FUNCIONA";
PFont fuente1;
int tiempoInicio;
int tiempoPagina;
int tiempoDialogo = 0;
int escena = 0;
int escena2 = 1;
int estado = 1;
float zoom = 1;
float xZoom = 0;
float yZoom = 0;
float xRiuk = 700;
float aura = 0;
float[] particulaX = new float[40];
float[] particulaY = new float[40];
